### ISSUE TITLE
Организации

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/guide_health_care#1]
Добавить в систему организации `Organization name:string description:text, address:string latitude:float longitude:float`. Кроме этого, через гем `geocoder` должны сохраняться координаты этого места.

Не должно быть двух организаций с одинаковым названием, однако могут быть организации с одинаковым адресом. Адрес должен быть распознан геокодером. Заполнять описание не обязательно. 

Управление организациями на уровне контроллера должно осуществляться в модуле `Panel`. Должны поддерживаться экшены: список организаций (пагинаций по 15, сортировка по алфавиту), создание, редактирование, удаление организации. 

Также, после реализации #2, на страницах создания/редактирования должна быть возможность привязывать болезни.

**Comment by kirshin** [comment]
1. Настроил среду для тестирования 962f46eea03289dcf0490131c5f405be2e9d05d5 
2. Добавил модель b1830432e12165573f772511133f803fa052d7f2
3. Добавил контроллер 90c2f89032f9baa676a71f0f114d81779aaba32e
4. Настроил rubocop e0b2ca3968c664daf58681ed37aab4e979f037fa
5. Добавил шаблоны 5e564b76150a561ee7348f505524f9faff5312b9 

Так как требований к гемам не было пока, решил взять инициативу в свои руки и предложить те гемы что я добавил, так же есть предложение использовать `https://github.com/bogdan/datagrid или https://github.com/leikind/wice_grid` и за основу для панели взять `css фреймворк bootstrap бесплатная тема для панели https://github.com/gurayyarar/AdminBSBMaterialDesign`

**Comment by kirshin** [comment]
1. Настроил модуль 394e1922b362b24e04011a77e5890b0f9ecc23e1
2. Добавил гем `grid` и вывел таблицу для организаций 9523ce44263b62ff653dd1ad96264f48ae300667
3. Добавил вложеную форму для привязки болезней 3171d9e2354fcea2b277344c8740cea1a03834e0

**Comment by IlyaDonskikh** [comment]
По поводу шаблона - нет. Слишком футуристично для офиса, который будет все это заполнять. Нужен очень классический подход, на примере панели для наших магазинов.

По поводу гридов - я не понимаю зачем это нужно делать, зависеть от гемов и левых стилей, когда самостоятельная реализация займет тоже количество времени и в рамках задачи не нужно пилить фичи, которые эти гемы поддерживают. Жду пояснений по этой части?

И когда я ставлю задачу у меня перед глазами всегда есть картинка результата, то что я ожидаю увидеть. В данном случае это совсем не ожиданный результат, который мешает мне планировать дальнейшую работу. Особенно рспеки, который 100% нужно согласовывать, так как их придется поддерживать и другим разработчикам проекта.

**Comment by kirshin** [comment]
Добавил 1116263270d148bc966285e8f4b7e46bacd62c8b

**Comment by IlyaDonskikh** [comment]
Очень хорошо. Можно закрывать.

**Comment by kirshin** [comment]
Ушло в `developer`
