### ISSUE TITLE
Болезни

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/guide_health_care#2]
Добавить в систему `illnesse name:string description:text  illnesse_id:integer` и `OrganizationIllnesse organization_id:integer  illnesse_id:integer`

У `illnesse` должно быть заполнено `name:string`. Кроме этого заболевания могут иметь иерархию, так что должна быть возможность указать родиельское заболевание через `illnesse_id`.

Управление заболеваниями на уровне контроллера должно осуществляться в модуле Panel. Должны поддерживаться экшены: список организаций (пагинаций по 15, сортировка по алфавиту), создание, редактирование, удаление.

**Comment by kirshin** [comment]
1. Добавил модель 1530baf8b01209118836965c714641c60a9a61c6
2. Добавил контроллер и шаблоны 45148b31ce6199a09ea41bb696635fc22f92f666
3. Отформатировал f5e04064e68fab4edd732516eb0df985a7426c26

**Comment by IlyaDonskikh** [comment]
грид, датагрид, бутстрап - все это нужно согласовывать как инструменты, до начала работы. Тоже самое об RSpec, вместо встроенных тестов. 

На данный момент оставляем, но в дальнейшей работе используй классические инструменты (тесты пусть RSpec  остаются).

**Comment by IlyaDonskikh** [comment]
В остальном - ништяк. Мерж в девелопер.

**Comment by kirshin** [comment]
Готово 3ad3bc30c381d3c0c91b2f4ba767812df1f4ea97

**Comment by IlyaDonskikh** [comment]
Ок. Мерж в девелопер и закрывай.

**Comment by kirshin** [comment]
Ушло в `developer`
