### ISSUE TITLE
Список организаций

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/guide_health_care#3]
Добавить в пользовательскую часть возможность просматривать список организаций и фильтровать их `OrganizationsController#index`.

Обрати внимание, что верстать нужно по схеме макета, но не нужно поддерживать стили. Другими словами, воспринимай макет как проектировочный. Обрати внимание, что выбор проблемы и адреса это ссылки. А поля формы будут заполняться через `hidden_field`. Результат нужно обновлять сразу после того, как значение поле `hidden_field` измениться.

Результаты обновляются через аякс в `OrganizationsController#index render :js`. Кроме того, расстояние до организации отображается, только если заполнено поле `Адрес`.

![main](https://cloud.githubusercontent.com/assets/3100222/19551878/1a0eaebc-96b6-11e6-8c26-dd42f1f94da8.jpg)

**Comment by kirshin** [comment]
1. Добавил контроллер f7064cd229f10441bc90a6e81d5be0bf4bae14e7
2. Добавил сортировку по дистанции 676d0fd7d4ed4410c8940ca88e955381072adb4c
3. Чуток верстки be479520dd150f7edcc658019ecd16b0ced56f7e

**Comment by IlyaDonskikh** [comment]
Отлично. Мерж в девелопер.

**Comment by kirshin** [comment]
Ушло в `developer`
