### ISSUE TITLE
Выбор адреса

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/guide_health_care#4]
Выбор адреса осуществляется через всплывающее окно, которое вызывается в `SelectPlacesСontroller#new render :js`. А утверждение организации через `SelectPlacesСontroller#create render :js`, в результате чего заполняется скрытое поле из задачи #3.

Выбрать адрес можно как через автокомплит, так и отметив точку на карте. В обоих случаях на карте должна появиться метка, а поле должно быть заполнено адресом.

![main](https://cloud.githubusercontent.com/assets/3100222/19552023/b6a32e1a-96b6-11e6-9f9e-3bf9fdbe48c7.jpg)

**Comment by kirshin** [comment]
Для всплывающего окна можно использовать `gem magnific-popup-rails` для автокомплита `gem jquery-ui-rails`?

**Comment by IlyaDonskikh** [comment]
Ага.

**Comment by kirshin** [comment]
Готово 40b4253a0d1ecbac86dff3ba975b26298eb76b43

Поиск по карте через стандартный поиск yandex map, поддерживаться перетаскивание метки, а так же клик в любое место карты

**Comment by IlyaDonskikh** [comment]
Давай в девелопер и закрывай задачу. Я уже там буду проверять.
