### ISSUE TITLE
Заполнить сиды

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/guide_health_care#5]
Заполни, пожалуйста, тестовые данные через сиды: http://edgeguides.rubyonrails.org/active_record_migrations.html#migrations-and-seed-data.

Это поможет быстрее тестировать работу.

**Comment by kirshin** [comment]
Я вот себе такие тестовые данные делал d85400c1227572d9e391fc611c8ba91268bf806f пойдут?

**Comment by IlyaDonskikh** [comment]
Норм, только еще болезни нужны в БД. Можешь после мержа #3 заполнить сиды уже в девелопере.

**Comment by kirshin** [comment]
Сделал 43bd3b6436a1806535a2b279d4b1f95aac50bb5f, ушло в `developer`

**Comment by IlyaDonskikh** [comment]
Сиды нужна для создания данных в любом энвироменте, а файлы ты поместил в папку для тестов, что логически не правильно. 

В данном случае, можно было бы добавить папку `import_data` в папку `db`. Погугли как правильно сделать.

Кроме того, когда закончишь с возрастами, то добавь их тоже в сиды.

**Comment by kirshin** [comment]
Обновил f23ea45830f7b61f987511d543a4d47a4a1caf49 сделал как ты рекомендовал, посмотрел как делают другие, обычно делают загрузку из фикстур

**Comment by IlyaDonskikh** [comment]
Думаю, что так как данные в сидах нужны для тестирования, то в этом есть какая-то логика. Но давай так оставим, потому что, скорее всего, мы будем выгружать реальные данные из файлов.

**Comment by kirshin** [comment]
По этой задаче все готово

**Comment by IlyaDonskikh** [comment]
Смерж в девелопер и закрывай.

**Comment by kirshin** [comment]
Ушло в `developer`
