### ISSUE TITLE
Выбор болезней

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/guide_health_care#6]
Выбор адреса осуществляется через всплывающее окно, которое вызывается в `SelectIllnessesСontroller#new render :js`. А выбор через `SelectIllnessesСontroller#create render :js`, в результате чего заполняется скрытое поле из задачи #3.

Выбрать болезнь можно, кликнув на ее ссылку. Фильтр отсеивает список болезней через JS, (без участия rails). Обрати внимание, что высота окна не более 580px и если болезни не помещаются в это окно, то появляется полоса прокрутки. 
## ![illnesses](https://cloud.githubusercontent.com/assets/3100222/19643200/c3babb0c-99f1-11e6-8640-2097a46434f2.jpg)

![illnesses_filtred](https://cloud.githubusercontent.com/assets/3100222/19643199/c3b6e0d6-99f1-11e6-9c3d-dd743c91ea98.jpg)

**Comment by kirshin** [comment]
Добавил 45f3107b2d0213ee574fed48002856924e69642d,
появились проблемы с пейджингом (неправильно формируеться SQL запрос) пока убрал

**Comment by kirshin** [comment]
Немного обновил поиск мест cc7258f7eda2089767641c68100c00a326592ced

**Comment by IlyaDonskikh** [comment]
Задачу можно считать закрытой?

**Comment by kirshin** [comment]
Да можно закрыть

**Comment by IlyaDonskikh** [comment]
Смерж в девелопер и закрывай.

**Comment by kirshin** [comment]
Ушло в `developer`
